import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from './components/SideBar'
import Container from './components/Container'
import BasketButton from './components/BasketButton'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex h-screen">
          <div className="w-72">
            <SideBar />
          </div>
          <div className="w-full h-screen">
            <Container>
              {children}
              <BasketButton/>
            </Container>
          </div>
      </body>
    </html>
  )
}
