import './globals.css'
import type { Metadata } from 'next'
import Header from './components/Header'
import Container from './components/Container'
import Chart from './components/Chart'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const isOpen = true;
  return (
    <html lang="en">
      <body className="flex">
          <div className={`h-screen overflow-auto bg-zinc-100 ${isOpen ? "w-full" : "w-screen" } transition-transform duration-300 ease-in-out`}>
            <Header />
            <Container>
              {children}
            </Container>
          </div>
          { isOpen &&
          <div className={`w-[450px] h-screen`}>
            <Chart />
          </div>
          }
      </body>
    </html>
  )
}
